### ISSUE TITLE
Add button to hide quote

### ISSUE THREAD

**Issue by DracoClaw** [AAGaming00/rich-quotes#101]
There should be a little x at the top right to hide the link preview, similar to what native discord allows for mods to remove an embed preview.

**Comment by MulverineX** [comment]
We do not intend to provide any message-active functionality for quoted messages, eg. you can't edit your message, add reactions, delete it, etc. The same applies for embeds, so if this were to be added, it would only be client-side, and what's the point of that if it's not cached. I'm not going to be putting in the time for that kind of polish for something so niche, and I doubt anyone else will. However, one of the issues message jumping in discord as a whole has is that it will frequently fail to get to the message, sometimes by a single page, others missing the mark entirely. This I intend to improve somehow in the future, which should make it less painful to navigate to the message for any active functions.

**Comment by DracoClaw** [comment]
I guess I didn't explain it well. I don't want any message action buttons. I'm talking about the message link preview that the plugin creates. Sometimes it can be quite large, or content you don't want to be seeing. Of course this would be client side as the link preview itself is client side.

**Comment by MulverineX** [comment]
OH lol, I understand now, yes that is a valid request
