### ISSUE TITLE
Fix broken shiet

### ISSUE THREAD

**Issue by MulverineX** [AAGaming00/rich-quotes#33]
- [x] Fix crashes with embeds
- [x] Fix embed color
- [x] Channel DM special case
- [x] Make default settings toggles not be retarded

**Comment by AAGaming00** [comment]
isnt the rerendering issue fixed?

**Comment by MulverineX** [comment]
> isnt the rerendering issue fixed?

Not the settings preview, the actual quotes in the channel you are currently on, a rerender does not occur until you swap channels (after closing settings).
