### ISSUE TITLE
Obscure channel preview rendering failure

### ISSUE THREAD

**Issue by ghost** [AAGaming00/rich-quotes#91]
![image](https://user-images.githubusercontent.com/71416098/100828176-13aded80-3491-11eb-8a21-e876b4827600.png)

Happens if you try to open Rich Quotes settings when you are in the friends tab
Minor Issue, just wanted to point out

**Comment by MulverineX** [comment]
Uh I can't reproduce this issue, what's your name on discord so we can discuss on the porkord discord? @transodonyx

**Comment by ghost** [comment]
Gleemys, ping me if u want to discuss it

**Comment by MulverineX** [comment]
Possibly connected to hardware, but this person is on an i5 from '17 & 8gb of RAM... mostly happens when on the friends tab (not in a channel/dm), very rarely can happen outside of it. Closing this because this is beyond me, can usually be avoided by being in a channel.
